# gitzone standard
image: hosttoday/ht-docker-node:npmci

cache:
  paths:
  - .yarn/
  key: "$CI_BUILD_STAGE"

stages:
- mirror
- test
- release
- trigger
- pages

mirror:
  stage: mirror
  script:
  - npmci git mirror
  tags:
  - docker
    
testSTABLE:
  stage: test
  script:
  - apt-get update && apt-get install -yq libgconf-2-4
  - apt-get update
  - apt-get install -y wget --no-install-recommends
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - apt-get update && apt-get install -y google-chrome-unstable --no-install-recommends
  - rm -rf /var/lib/apt/lists/*
  - apt-get purge --auto-remove -y curl
  - rm -rf /src/*.deb
  - npmci node install stable
  - npmci npm install
  - npmci npm test
  coverage: /\d+.?\d+?\%\s*coverage/
  tags:
  - docker

release:
  stage: release
  script:
  - npmci npm prepare
  - npmci npm publish
  only:
  - tags
  tags:
  - docker

trigger:
  stage: trigger
  script:
  - npmci trigger
  only:
  - tags
  tags:
  - docker

pages:
  image: hosttoday/ht-docker-node:npmci
  stage: pages
  script:
    - npmci command yarn global add npmpage
    - npmci command npmpage
  tags:
    - docker
  only:
    - tags
  artifacts:
    expire_in: 1 week
    paths:
    - public
